### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by karl-project-review** [brianejsmont/intro-data-capstone-biodiversity#5]
(Needs Improvement)

This project is nearly there! Most of your code does exactly what it should, and your plots present the data clearly. Also, your presentation slides on the significance of the data and your recommendations are direct and appropriate given your computations.

There are a few places where uniqueness of the data is not taken into account. While this doesn't have too big of an effect on your conclusions in this case, it could have if there were more duplicates in the data, so it is worth going back and fixing this. Also, making sure our input for the minimal detectable effect is correct will have a large impact on the sheep study, so that is also something to take another look at.

Again, this is pretty close to being right. There are just a few lines that need to be fixed, but they are very important lines. Good work and keep at it!

**Comment by brianejsmont** [comment]
Thanks for the feedback. I've opened a PR (https://github.com/brianejsmont/intro-data-capstone-biodiversity/pull/6) with the changes. Please let me know how I should proceed to get a second look.

**Comment by karl-project-review** [comment]
You only get one review, I'm afraid. The 'needs improvement' doesn't mean you need to show any revisions to us (the course just requires that you submit it once), but rather that we'd recommend going through the process of doing the revisions in order to ensure you are mastering the material (so kudos to you for putting in the time to do so). Have a great day!
